#!/usr/bin/env bash

set -e -o pipefail

cd "$(dirname "$0")/.."

rm -rf dist/*

npm exec tsup

(cd dist && node -e 'require("@xct007/midtrans-client")')
(cd dist && node -e 'import("@xct007/midtrans-client")' --input-type=module)
