#!/usr/bin/env bash

set -e -o pipefail

cd "$(dirname "$0")/.."

rm -rf dist; mkdir dist

npm exec tsc-multi

cp dist/index.d.ts dist/index.d.mts

(cd dist && node -e 'require("@xct007/midtrans-client")')
(cd dist && node -e 'import("@xct007/midtrans-client")' --input-type=module)
